//conditional params test
pipeline {
 agent any

 parameters {
    choice(
        choices: ['apply' , 'destroy'],
        description: 'Deploy/change or destroy TF assets',
        name: 'REQUESTED_ACTION')
}
 
 stages {
 stage('checkout') {
 steps {
 git branch: 'master', url: 'https://github.com/clarksm/terraform.git'
 
 }
 }
 
 stage('Infrastructure Apply') {
 
 when {
    // Apply TF infrastructure
    expression { params.REQUESTED_ACTION == 'apply' }
}
 steps {
 dir('aws')
 {
 sh 'terraform init'
 sh 'terraform plan -out=plan'
 sh 'terraform apply plan'
 sh 'aws ec2 describe-instances --filter "Name=instance-state-name,Values=running,Name=tag:Environment,Values=Dev" --query "Reservations[].Instances[].[PublicIpAddress]" --output=text > ../../../hosts/devhosts.txt'
 sh 'aws ec2 describe-instances --filter "Name=instance-state-name,Values=running,Name=tag:Environment,Values=Prod" --query "Reservations[].Instances[].[PublicIpAddress]" --output=text > ../../../hosts/prodhosts.txt'
 }
 
 
 }
 }

stage('Infrastructure Destroy') {
 
 when {
    // Destroy TF infrastructure
    expression { params.REQUESTED_ACTION == 'destroy' }
}
 steps {
 dir('aws')
 {
 sh 'terraform destroy -auto-approve'
 }
 
 
 }
 }
 
 
 
 }
}
