pipeline {
 agent any

 parameters {
    choice(
        choices: ['apply' , 'destroy'],
        description: 'Deploy/change or destroy TF assets',
        name: 'REQUESTED_ACTION')
}
 
 stages {
 stage('checkout') {
 steps {
 git branch: 'master', url: 'https://github.com/clarksm/terraform.git'
 
 }
 }
 
 stage('Infrastructure Apply') {
 
 when {
    // Only say hello if a "greeting" is requested
    expression { params.REQUESTED_ACTION == 'apply' }
}
 steps {
 dir('aws')
 {
 sh 'terraform init'
 sh 'terraform plan -out=plan'
 // sh ‘terraform destroy -auto-approve’
 sh 'terraform apply plan'
 }
 
 
 }
 }

stage('Infrastructure Destroy') {
 
 when {
    // Only say hello if a "greeting" is requested
    expression { params.REQUESTED_ACTION == 'destroy' }
}
 steps {
 dir('aws')
 {
 sh 'terraform destroy -auto-approve'
 }
 
 
 }
 }
 
 
 
 }
}
